model: openrouter/openai/o3-mini-high
editor-model: openrouter/anthropic/claude-3.5-sonnet
weak-model: openrouter/anthropic/claude-3-5-haiku
architect: true
auto-commits: true
auto-test: true
test-cmd: "go test cmd/main_test.go"
auto-lint: true
lint-cmd: "golangci-lint run"
read: CONVENTIONS.xml
